### ISSUE TITLE
BreadcrumbsHelper not being loaded in Rails 3

### ISSUE THREAD

**Issue by ashrewdmint** [roidrage/crumble#9]
I was getting a "no method error" when I tried to use the `crumbs` method in my views. When I manually copied the BreadcrumbsHelper and put it in my Rails app, it worked. It seems like the helper isn't getting included successfully.

**Comment by roidrage** [comment]
I take you used the latest version of the gem and not something built from master right? Someone already provided a patch to make it work with Rails 3, I just haven't gotten around to making a new gem yet. Will do so today.

**Comment by ashrewdmint** [comment]
Yeah, I'm using the gem, that must be the problem. Thanks for the plugin :)

**Comment by roidrage** [comment]
Just pushed a new version of the gem. Let me know if that solves the problem.

**Comment by ashrewdmint** [comment]
It works now, thanks!

**Comment by hernanvicente** [comment]
SOLVED: The solution is not use the helper calling in affected controllers because this is loaded automaticly in the application ActionController::Base.helper(BreadcrumbsHelper), so the helper is accessed from all app/controllers.

Please if you may update your Usage section in Readme.

---

Hi mattmatt,

we are trying to use the gem but we get yet the same error:

Started GET "/" for 127.0.0.1 at Thu Nov 18 20:00:57 -0500 2010

LoadError (Missing helper file helpers/breadcrumbs_helper.rb):
  app/controllers/pages_controller.rb:2

We have added the initializer and the helper calling to our controller "Pages".

Our enviroment is:
Ruby 1.9.2
Rails 3.0.1
Crumble 0.1.3

We have browsed the directory gem and we found the breadcrumb helper file, Rails is not loading the helper file from the gem.

Thanks,
Hernan

**Comment by denniscastro** [comment]
Hi everybody
I just use the gem in rails 3, it works fine.. do not trust in the documentation file

:P

Dennis C.
